# Generated by Django 2.2.1 on 2019-05-24 18:15

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('login', '0002_auto_20190524_1343'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
